securecodebox:
  telemetryEnabled: false
  minio:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      path: /
      pathType: Prefix
      hostname: &host minio.atte.cloud
      extraTls:
        - hosts:
            - *host
          secretName: minio-tls-certificate
