apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.osdfir.timesketch.postgresql.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: {{ .Values.osdfir.timesketch.postgresql.auth.username }}
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /timesketch/postgres
        property: password
        conversionStrategy: Default
        decodingStrategy: None
