apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.harbor.core.configOverwriteJsonSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.harbor.core.configOverwriteJsonSecret }}
    template:
      engineVersion: v2
      data:
        # TODO: can the client_secret value be properly escaped? 
        # a double quote in the client_secret pulled from vault will break the json. For now, mitigated
        # during secret creation (no special chars).
        overrides.json: |
          {
            "auth_mode": "oidc_auth",
            "oidc_name": "Dex",
            "oidc_endpoint": "https://dex.atte.cloud",
            "oidc_client_id": "harbor-sso",
            "oidc_client_secret": {{` "{{ .HARBOR_SSO_CLIENT_SECRET }}"  `}},
            "oidc_verify_cert": true,
            "oidc_scope": "openid,profile,email,offline_access,groups",
            "oidc_group_filter": "ops",
            "oidc_groups_claim": "groups"
          }
  data:
    - secretKey: HARBOR_SSO_CLIENT_SECRET
      remoteRef:
        key: /dex/harbor
        property: client_secret