apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: harbor-secrets
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: /harbor/admin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: HARBOR_CLIENT_SECRET
      remoteRef:
        key: /dex/harbor
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None