kube-prometheus-stack:
  grafana:
    adminPassword: null
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Grafana
        hajimari.io/icon: chart-bar
      hosts:
        - &host grafana.atte.cloud
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    envFromSecret: grafana-secrets
    grafana.ini:
      server:
        root_url: https://grafana.atte.cloud
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        name: Dex
        client_id: grafana-sso
        client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
        scopes: openid profile email groups
        auth_url: https://dex.atte.cloud/auth
        token_url: https://dex.atte.cloud/token
        api_url: https://dex.atte.cloud/userinfo
  kubeApiServer:
    enabled: true
  kubeControllerManager:
    enabled: true
    endpoints:
      - metal0
    service:
      enabled: true
      port: 10257
      targetPort: 10257
    serviceMonitor:
      enabled: true
      https: true
      insecureSkipVerify: true
  kubeScheduler:
    enabled: true
    endpoints:
      - metal0
    service:
      enabled: true
      port: 10259
      targetPort: 10259
    serviceMonitor:
      enabled: true
      https: true
      insecureSkipVerify: true 
  kubeProxy:
    enabled: true
    endpoints:
      - metal0
  kubeEtcd:
    enabled: true
    endpoints:
      - metal0
    service:
      enabled: true
      port: 2381
      targetPort: 2381
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
