drone:
  ingress:
    enabled: true
    className: nginx
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host ci.atte.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: drone-tls-certificate
        hosts:
          - *host
  persistentVolume:
    enabled: true
    storageClassName: longhorn
  extraSecretNamesForEnvFrom:
    - drone-env-secret
  env:
    DRONE_SERVER_HOST: ci.atte.cloud
    DRONE_SERVER_PROTO: https
    DRONE_GITEA_SERVER: https://git.atte.cloud


