dex:
  config:
    issuer: https://dex.atte.cloud
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: gitea
        id: gitea
        name: Gitea
        config:
          clientID: $GITEA_CLIENT_ID
          clientSecret: $GITEA_CLIENT_SECRET
          redirectURI: https://dex.atte.cloud/callback
          baseURL: https://git.atte.cloud
          orgs:
            - name: ops
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.atte.cloud/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: harbor-sso
        name: Harbor
        redirectURIs:
          - 'https://harbor.atte.cloud/c/oidc/callback'
        secretEnv: HARBOR_SSO_CLIENT_SECRET
      - id: concourse-sso
        name: Concourse
        redirectURIs:
          - https://ci.atte.cloud/sky/issuer/callback
        secret: concourse-sso-secret # TODO: use vault
      - id: argocd-sso
        name: ArgoCD
        redirectURIs:
          - https://argocd.atte.cloud/auth/callback
        secretEnv: ARGOCD_SSO_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets    
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: 'false'
    hosts:
      - host: &host dex.atte.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-tls-certificate
        hosts:
          - *host
