gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.atte.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.atte.cloud
      webhook:
        ALLOWED_HOST_LIST: private
      service:
        REGISTER_MANUAL_CONFIRM: true
      log:
        ENABLE_ACCESS_LOG: true
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
