gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.atte.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.atte.cloud
      webhook:
        ALLOWED_HOST_LIST: private
      service:
        REGISTER_MANUAL_CONFIRM: true
      log:
        ENABLE_ACCESS_LOG: true
      ui:
        DEFAULT_THEME: catppuccin-mocha-teal
        THEMES: auto,gitea,arc-green,catppuccin-mocha-teal
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
  extraContainerVolumeMounts:
    - name: gitea-themes
      mountPath: /data/gitea/public/css
    - name: gitea-themes
      mountPath: /data/gitea/public/img
  extraVolumes:
    - name: gitea-themes
      configMap:
        name: gitea-custom-theme-cm
    - name: gitea-logos
      configMap:
        name: gitea-custom-logos-cm

