defectdojo:
  imagePullPolicy: IfNotPresent
  host: &host dojo.atte.cloud
  django:
    ingress:
      enabled: true
      ingressClassName: nginx
      secretName: defectdojo-tls-certificate
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        #nginx.ingress.kubernetes.io/auth-url: "https://oauth.atte.cloud/oauth2/auth"
        #nginx.ingress.kubernetes.io/auth-signin: "https://oauth.atte.cloud/oauth2/start?rd=$escaped_request_uri"

  createSecret: false
  createRabbitMqSecret: false
  createPostgresqlSecret: false
