harbor:
  global:
    storageClass: longhorn
  exposureType: ingress
  ingress:
    core:
      hostname: harbor.atte.cloud
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"  
      tls: true
    notary:
      hostname: notary.atte.cloud
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      tls: true
  externalURL: https://harbor.atte.cloud
  core:
    extraEnvVarsSecret: harbor-secrets # TODO: pull other initial secrets (database, redis) from secrets.
    configOverwriteJsonSecret: harbor-config-overwrite-secret
  persistence:
    enabled: true
    resourcePolicy: keep
  redis:
    enabled: true