
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {

        root /www;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
