apiVersion: v1
kind: Service
metadata:
  name: {{ include "yeti.fullname" . }}-frontend
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yeti.frontend.selectorLabels" . | nindent 4 }}
