#!/bin/sh

export KUBECONFIG=./metal/kubeconfig.yaml

NAMESPACES=$(kubectl get namespace | awk '{print $1}' | tail -n +2)

for ns in $NAMESPACES
do
    EXTERNALSECRETS=$(kubectl get es -n "$ns" -o jsonpath="{.items..metadata.name}")
    for es in $EXTERNALSECRETS
    do
        kubectl annotate es "$es" force-sync="$(date +%s)" -n "$ns" --overwrite
    done
done
