k3s_version: v1.24.9+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_server_config:
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-cloud-controller: true
  secrets-encryption: true
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true