# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- path: dex/grafana
  data:
    - key: client_secret
      length: 32
      special: false

# Harbor
- path: harbor/admin
  data:
    - key: password
      length: 32
      special: true

- path: dex/harbor
  data:
    - key: client_secret
      length: 32
      special: false

# Tekton
- path: tekton/webhook
  data:
    - key: token
      length: 32
      special: false

# Drone
- path: drone/rpc
  data:
    - key: secret
      length: 32
      special: false