# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- path: dex/grafana
  data:
    - key: client_secret
      length: 32
      special: false

# Harbor
- path: harbor/admin
  data:
    - key: password
      length: 32
      special: false

- path: dex/harbor
  data:
    - key: client_secret
      length: 32
      special: false

# Tekton
- path: tekton/webhook
  data:
    - key: token
      length: 32
      special: false

# ArgoCD
- path: dex/argocd
  data:
    - key: client_secret
      length: 32
      special: false

# OAuth2Proxy
- path: dex/oauth2proxy
  data:
    - key: client_secret
      length: 32
      special: false

- path: oauth2proxy/cookie
  data:
    - key: cookie_secret
      length: 32
      special: false

- path: timesketch/postgres
  data:
    - key: postgres-password
      length: 32
      special: false
    - key: password
      length: 32
      special: false
    - key: replication-password
      length: 32
      special: false
