apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: concourse-main-team-harbor-credentials
  namespace: {{ .Release.Namespace }}-main
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: harbor-robot
  data:
    - secretKey: name
      remoteRef:
        key: /harbor/tekton-robot-account
        property: name
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: token
      remoteRef:
        key: /harbor/tekton-robot-account
        property: secret
        conversionStrategy: Default
        decodingStrategy: None